[tool.poetry]
name = "TransparentEmail"
version = "0.1.0"
description = ""
authors = ["Akash Gupta"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
black = "^21.7b0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
